CREATE TABLE consumer_complaint(
   DATE_RECEIVED                VARCHAR(255)
  ,PRODUCT                      VARCHAR(255)
  ,SUBPRODUCT                   VARCHAR(255)
  ,ISSUE                        VARCHAR(255)
  ,SUBISSUE                     VARCHAR(255)
  ,CONSUMER_COMPLAINT_NARRATIVE VARCHAR(255)
  ,COMPANY_PUBLIC_RESPONSE      VARCHAR(255)
  ,COMPANY                      VARCHAR(255)
  ,STATE                        VARCHAR(255)
  ,ZIP_CODE                     VARCHAR(255) 
  ,SUBMITTED_VIA                VARCHAR(255) 
  ,DATE_SENT_TO_COMPANY         VARCHAR(255)
  ,COMPANY_RESPONSE_TO_CONSUMER VARCHAR(255) 
  ,TIMELY_RESPONSE              VARCHAR(255) 
  ,CONSUMER_DISPUTED            VARCHAR(255)
  ,COMPLAINT_ID                 VARCHAR(255)
);